export { AppContent } from './AppContent';
export { Discover } from './Discover';
export { DiscoverEnd } from './DiscoverEnd';
export { Assesment } from './Assesment';
export { PracticePage } from './Practice';
export { HomePage } from './HomePage';
export { NoPageFound } from './NoPageFound';
export { AssesmentEnd } from './AssesmentEnd';
export { DiscoverStart } from './DiscoverStart';
